### ISSUE TITLE
caret state is lost after undo / redo

### ISSUE THREAD

**Issue by mydearxym** [kommitters/editorjs-undo#10]
hi guys 

as mentioned in https://github.com/codex-team/editor.js/issues/518#issuecomment-659056422, when i use this plugin in editor.js, the [caret state](https://editorjs.io/caret) (like previous cursor position staff) is lost，it's there a way to keep the cursor state after undo/redo ?

thanks!

**Comment by nicolasgaviria** [comment]
@mydearxym Thank you! I'll check it as soon as I can.

**Comment by nicolasgaviria** [comment]
Hi @mydearxym, so sorry for the delay. In this [branch](https://github.com/kommitters/editorjs-undo/tree/keep-caret-state) I uploaded something that I think solves the issue. Can you please check it and tell me if it works for you? Thanks!

**Comment by mydearxym** [comment]
@nicolasgaviria  i have tried this branch on my local project,  it works like magic !  👍

**Comment by nicolasgaviria** [comment]
@mydearxym Awesome! I'll include it in the next release. Thanks!

**Comment by juanhurtado10** [comment]
Closing this! fixed in the v1.03
