### ISSUE TITLE
Undo with CMD+Z does not work across multiple blocks

### ISSUE THREAD

**Issue by trevrdspcdev** [kommitters/editorjs-undo#102]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

If a user makes changes in more than one block and tries to undo those changes with CMD+Z, the plugin breaks and unexpectedly deletes a block when it should not.

### Environment

* Editor.js version: 2.23.2
* Plugins you use with their versions: editorjs-undo (2.0.0-rc.3)
* Device, Browser, OS: Macbook Pro, Chrome, MacOS

### Current behavior

The plugin unexpectedly deletes content during CMD+Z operations across multiple blocks, as shown below:

https://user-images.githubusercontent.com/19937217/159501773-09e041c2-528d-4c9d-861f-13a1f240e380.mov

To recreate this bug, take the following steps:

1. Enter some text in a paragraph block
2. Press enter and enter some text in a new paragraph block
3. Select and delete some of the text in the first paragraph block
4. Select and delete some of the text in the second paragraph block
5. Press CMD+Z
6. Notice that the second paragraph block is deleted
7. Press CMD+Z
8. Notice that the following error is thrown:
<img width="469" alt="no-block-at-index-1" src="https://user-images.githubusercontent.com/19937217/159501325-1d629bc9-2a9b-44d5-878a-5413c7c1c4f1.png">

### Expected behavior

Undo operations with CMD+Z should work properly across multiple blocks instead of having content deleted unexpectedly, as shown below:

https://user-images.githubusercontent.com/19937217/159503247-479c187d-5e26-4714-be0f-473d19357faa.mov

### Additional context

The plugin is currently incorrectly deleting a block when it should not because no entry is inserted into the stack when a user moves between blocks. This causes the `blockWasSkipped` function to return `true` when it should not. It compares the `index` and `compIndex` obtained from the stack, and since there was no stack entry for when the user switched from one block to another, this condition evaluates to `true` and the second block in the example I provided gets deleted.

<img width="962" alt="block-was-skipped-function" src="https://user-images.githubusercontent.com/19937217/159505570-f638a87e-49de-4c05-85f4-e420f659c3ee.png">
<img width="861" alt="if-block-was-skipped" src="https://user-images.githubusercontent.com/19937217/159505575-8dfa55c4-e12c-4dfc-9cd0-f24dd42c5872.png">

For what it's worth, I did attempt to implement a fix for this issue by modifying the `blockWasSkipped` function to no longer do an index comparison and also adding a new click listener/handler to save and insert new stack entries when the user switched between blocks, but my solution did not seem stable across environments. These changes are shown below:

<img width="801" alt="block-was-skipped-function-modified" src="https://user-images.githubusercontent.com/19937217/159508742-a683a11e-dade-456c-afbc-ad5470fde8e6.png">
<img width="808" alt="handle-click-function" src="https://user-images.githubusercontent.com/19937217/159508746-e449f292-2ae6-44fe-9ced-a4956b7e23e0.png">

Unfortunately I do not have the bandwidth to continue looking into a solution for this issue, so I'm hoping someone in the community can solve it and that the information I've provided here helps with that effort.

**Comment by MarioRodriguezS** [comment]
@trevrdspcdev Hi there!
Thanks a lot for reporting the issue, it was solved in the pull request #108 and it will be available in the version v2.0 soon. 

Best,
Mario
