### ISSUE TITLE
Unable to set CMD+SHIFT+Z as redo shortcut

### ISSUE THREAD

**Issue by hlynurstef** [kommitters/editorjs-undo#106]
### Description

I always use cmd+z for undo and cmd+shift+z for redo in every application I use so I wanted to set the same shortcuts for this library. However if I set it up like that then both cmd+z and cmd+shift+z will perform an undo action.

My configuration:

```
const undo = new Undo({
  editor,
  config: {
    shortcuts: {
      undo: "CMD+Z",
      redo: "CMD+SHIFT+Z",
    },
  },
});
```

### Environment

* Editor.js version: `2.23.2`
* Plugins you use with their versions: `editorjs-undo: 2.0.0-rc.3`
* Device, Browser, OS: Apple M1 Pro, Chrome Version 100.0.4896.60 (Official Build) (arm64), MacOS Monterey Version 12.2.1

### Current behavior

Having both cmd+z as undo and cmd+shift+z as redo in the shortcuts config will result in both performing an undo action.

### Expected behavior

The shortcuts should respect the config sent into Undo.

**Comment by christoph-kluge** [comment]
I can confirm this behavior (just started to play around with this plugin).

**Comment by MarioRodriguezS** [comment]
@hlynurstef @christoph-kluge Hi there! 
Thanks a lot for reporting the issue, it was solved in #109 and the solution will be available in the version v2.0 soon. 

Best,
Mario.

**Comment by hlynurstef** [comment]
@MarioRodriguezS thank you ❤️

**Comment by christoph-kluge** [comment]
@MarioRodriguezS thank you 👍 Do you have an ETA for v2.0? 

I recall that I was playing with v2-rc as well and it didn't worked out.

Will will test it again as soon as v2 will be released.

**Comment by MarioRodriguezS** [comment]
@christoph-kluge @hlynurstef  Hi there!

The v2.0 has just been released. Thanks!
