### ISSUE TITLE
2.0.0-rc3 - TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by christoph-kluge** [kommitters/editorjs-undo#107]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

If you add an empty paragraph, followed by an empty paragraph and enter one character: You're receiving the following message:

```
bundle.js?:formatted:347 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at t.value (bundle.js?:formatted:347:54)
    at eval (bundle.js?:formatted:329:62)
```

### Environment

* Editor.js version: 2.23.2
* Plugins you use with their versions: 2.0.0-rc3
* Device, Browser, OS: Monterey 12.3, Safari Version 15.4 (17613.1.17.1.6)

### Current behavior

1. Load the editor with an initial header
2. Click Enter (creates a new block)
3. Click again Enter (creates another new block)
4. Enter any character (i.e. "a") inside the second block and you should see the error message

### Expected behavior

The error message should not appear.

### Additional context

Using react-editor-js as described in the README.md with `onInitialize`.

```
  const handleInitialize = React.useCallback((instance) => {
    editorCore.current = instance
  }, [])

  const handleReady = () => {
    const editorJsInstance = editorCore.current._editorJS;
    const undo = new Undo({
      editor: editorJsInstance,
      config: {
        debounceTimer: 100
      }
    });
    undo.initialize(editor.blocks);
    new DragDrop(editorJsInstance);
  };
```

**Comment by MarioRodriguezS** [comment]
@christoph-kluge Thanks a lot for reporting the issue, it was solved in #110 and the solution will be available in v2.0 soon. 
Also, remember that editorjs-undo will ignore empty blocks unless they have been set in the EditorJs instance as follows:

https://github.com/editor-js/paragraph#config-params

Best,
Mario.
