### ISSUE TITLE
Moving blocks (or Drag and Drop) + Undo seems squishy

### ISSUE THREAD

**Issue by christoph-kluge** [kommitters/editorjs-undo#117]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

It seems that moving blocks (via Drag-and-Drop OR via BlockTune) doesn't behave consistently.

### Environment

* Editor.js version: 2.24.2
* Plugins you use with their versions:
  * `"@editorjs/header": "^2.6.2"`
  * `"@editorjs/paragraph": "^2.8.0"`
* Device, Browser, OS:
  * Mac
  * Safari Version 15.4 (17613.1.17.1.6)
  * OSX Moneterey 12.3

### Current behavior

1. Move via Drag and Drop to last position.
2. Press Undo-Combination
3. First Paragraph is missing. Last two Paragraphs are duplicate

### Expected behavior

1. Move via Drag and Drop to last position
2. Press Undo-Combination
3. First and Last Paragraph should be switched correctly

### Additional context

Attached 2 Videos with two different behaviors

#### Bug with Drag and Drop 

https://user-images.githubusercontent.com/1446269/167936531-2daca295-ff9f-46a0-83fb-151860eeac47.mov

#### Bug with BlockTune

https://user-images.githubusercontent.com/1446269/167936589-d322b867-fcb6-46ca-9ad8-c50020434edd.mov

**Comment by MarthoxGT** [comment]
Greetings @christoph-kluge.

Thanks a lot for raising this issue, I'll check if maybe a fix related with the drag'n drop plugin (https://github.com/kommitters/editorjs-drag-drop/issues/83) fix this issue already, if not I'll give it a look to see how we can fix this

**Comment by MarthoxGT** [comment]
Hey @christoph-kluge, hope you doing well.

In the last release of the plugin (v2.0.2) there should be the solution for this issue, if it persists please let us know.

**Comment by christoph-kluge** [comment]
@MarthoxGT @juanhurtado10 I did a quick test and I'm still facing this issue.

```
    "editorjs-drag-drop": "^1.1.2",
    "editorjs-undo": "^2.0.2",
```

**Comment by christoph-kluge** [comment]
I was curious and created a sandbox scenario. It seems it is fixed as soon as I isolate the behavior in a sandbox.

https://codesandbox.io/s/editor-js-drag-and-drop-undo-xpnmk8

Will dig deeper to identify why it's failing in my project.

**Comment by MarthoxGT** [comment]
That'll help us a lot @christoph-kluge, thank you a lot for the time you're putting into.

Maybe deleting your node_modules folder and creating them again (if you haven't done it yet) could fix the issue in your local.

We are going to be attentive to your updates.

Mealwhile I'm going to try to replicate the issue with less ideal scenarios to see if I can find something.

Best regards.

**Comment by christoph-kluge** [comment]
I could validate that it works with dynamic data as soon as I remove the `id` property like this:

```
    undo.initialize([...normalizedInput.blocks].map(block => {
      if (block.hasOwnProperty('id')) {
        delete block.id
      }
      return block
    }));
```

I guess there's some magic or comparison related to the `id`?

**Comment by MarthoxGT** [comment]
Ohh nice, thanks a lot for the update, I'll reopen the issue to keep working on a solution.

And again thanks a lot, I really appreciate it!

**Comment by MarthoxGT** [comment]
Hey @christoph-kluge, hope you're doing great!

There's up a new release ([v2.0.3](https://github.com/kommitters/editorjs-undo/releases/tag/v2.0.3)) where I tested the case you sent to us in the sandbox, and for me it seems to be working smoothly, please let us know if it fix the problem

Thanks for your time! Best regards

**Comment by christoph-kluge** [comment]
I've updated my local version and reverted the workaround. It seems that it's all good now. Closing here.

Thank you so much for the quick repsonse 🙏
