### ISSUE TITLE
Undo is ignored, when Copy-paste 2-3 paragraph from Wikipedia

### ISSUE THREAD

**Issue by Ashish-Raturi** [kommitters/editorjs-undo#143]
Hi, thanks for this package. I'm getting a bug. Can you help me.
When a user pastes text into the editor and uses the 'undo' function, then it should undo the paste.
Instead, the undo is ignored.

Steps to reproduce:
01. Go to Wikipedia
02. Select and copy 2-3 paragraph
03. Paste in the editor.
04. Then the editor ignores the undo & redo.

Expected behavior:
The editor should undo the paste.

**Comment by santiagoboterokommit** [comment]
@Ashish-Raturi Thanks for your report, we solved it and it is available in the 2.0.7 version
