### ISSUE TITLE
undo redo not working for underline and change case and redo not working for hyperlink

### ISSUE THREAD

**Issue by indusee** [kommitters/editorjs-undo#157]
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Environment

* Editor.js version:
* Plugins you use with their versions:
* Device, Browser, OS:

### Current behavior

Include code samples, errors and stack traces if appropriate.
If reporting a bug, please include the reproducing steps.

**Comment by indusee** [comment]
Plugins you use with their versions: "@editorjs/underline": "^1.0.0",  "editorjs-change-case": "0.0.3",   "editorjs-undo": "^2.0.9",
Device, Browser, OS: Dell , Googlecrome Version 106.0.5249.121 (Official Build) (64-bit), Microsoft Windows 10pro, editorjs:ReactEditorJs

**Comment by indusee** [comment]
i am getting this error in console 
client.js:36 Uncaught (in promise) TypeError: Cannot destructure property 'blocks' of 'editor' as it is undefined.
    at new Undo (index.js:33:1)
    at onReady (ViewOnBoarding.js:1192:1)
    at editor.js:2:1

**Comment by karolrojas07** [comment]
Hi, @indusee, I hope you are doing well.
I have been trying to reproduce the error you mentioned. 
And, I did undo and redo actions for only text blocks:
 
![text](https://user-images.githubusercontent.com/100703669/199610607-5712637b-9936-4494-81ee-9859642a8ad9.gif)

And also using the other plugins you mentioned, underline and change-case:
![Text2](https://user-images.githubusercontent.com/100703669/199613883-4d29a6e0-bb0b-48c2-9711-a75cecaca50d.gif)

But, I can't get your error. So, please, can you provide us a detailed description with steps to reproduce the error you reported?

Thanks.

**Comment by indusee** [comment]
https://codesandbox.io/p/github/indusee/undo-redo_bug/draft/exciting-austin?file=%2Fsrc%2FcreateServiceWorker.js
(please once run this code, I was tested here undo redo not working for underline plugin, please mention where I did mistake)

**Comment by karolrojas07** [comment]
Hi, @indusee. I have great news, here a left you a Sandbox, where you can see how to use this Undo plugin using react-editor-js into a React Component class:
https://codesandbox.io/embed/react-editor-js-v2-forked-kct1je?fontsize=14&hidenavigation=1&theme=dark

First, you have to import the library:
`import Undo from "editorjs-undo";`

Then, add the constructor and the following two functions into the class:
`constructor(props) {
    super(props);
    this.editorCore = React.createRef();
  }`

  `handleInitialize = (instance) => {
    this.editorCore.current = instance;
  };`

 `handleReady = () => {
    const editor = this.editorCore.current._editorJS;
    new Undo({ editor });
  };`

And, finally, into the ReactEditorJS element add these attributes:
`onInitialize={this.handleInitialize}`
`onReady={this.handleReady}`

Also, here you can see that it is working using the underline and change-case plugins
![UndoSandbox](https://user-images.githubusercontent.com/100703669/201445874-a5f72b9d-44b4-4649-8330-c1a49c69625b.gif)

**Comment by miguelnietoa** [comment]
Closing this as the usage instructions for React have been added and released on version `2.0.14`!
