### ISSUE TITLE
Undo issue related to editorjs

### ISSUE THREAD

**Issue by sos-productions** [kommitters/editorjs-undo#16]
As Undo plugin need an inital state 
`
function initUndo() {
    
        undo = new Undo({editor});
          
        editor.save().then((outputData) => {
            //console.log('Article data: ', outputData) //strong tags are washed where are they are allowed in config
            var initialData=outputData
            undo.initialize(initialData.blocks);
        }).catch((error) => {
            console.log('Saving failed: ', error)
        });
    }
`

and in my paragaph plugin config, I have

   paragraph: {
                text: {
                    type: "string",
                    allowedTags: "i,b,u,a[href],strong,em,br,br,dt,dl,embed,ol,li,ul"
                }
            }
`
but edtor sanitize at least strong tag (and I guess others too) on editor.save()
`
 /**
        * Saving example
        */
    
        saveButton.addEventListener('click',(e) => {
                editor.save().then((savedData) => {
                    alert(savedData.toSource()) //<strong> dissaper
                });
        }); 
`

so when I undo, I got only text with br tag preserved in paragraph

**Comment by Jmzp** [comment]
Hi @sos-productions, can you provide me with the sample text that you use?

**Comment by sos-productions** [comment]
Hi @Jmzp,

I just created a paragraph with some styling like strong, I took the topic from chapter 3 of the excellent https://www.theepochtimes.com/c-how-the-specter-of-communism-is-ruling-our-world ...choose
the table of content loaded in editorjs   seen as a paragraph which json is
`
  {
            type : 'paragraph',
            data : {
              text : `text:<strong>Introduction</strong><br><strong>1. The Rise of Totalitarian Communism</strong><br>\na. The Soviet Communists\u2019 Rise to Power<br>\nb. The Chinese Communist Party\u2019s Power Grab<br><strong>2. The Brutality of Communist Rule</strong><br>\na. Soviet Communist Atrocities<br>\n\u2013 Killing by Famine<br>\n\u2013 The Gulags: Europe\u2019s First Concentration Camps<br>\n\u2013 The Great Terror Against the Soviet Elite<br>\nb. The CCP\u2019s Deadly Campaigns<br>\n\u2013 The Great Chinese Famine<br>\n\u2013 The Cultural Revolution: Slaughter and Cultural Genocide<br>\n\u2013 Unprecedented Evil: The Persecution of Falun Gong<br><strong>3. A Century of Killing</strong><br><strong>References</strong>`
            }
          }
`


As I told you, if make a little change on the paragraph and undo , it is was washing all the tags including strong. 
due to the call `this.editor.save().then((savedData) => {`

Now I fixed it with a patch  on editor.js I submitted here https://github.com/codex-team/editor.js/pull/1281 , waiting
to be approved. I rebuild the edidor with ./build helper script
and set editor.save(true) on the call line 81 in index.js of Undo plugin

I rebuilt too Undo Plugin and it works like a charm.
