### ISSUE TITLE
Shortcuts are not supported on other keyboard layouts

### ISSUE THREAD

**Issue by NeoKms** [kommitters/editorjs-undo#167]
### Precheck

- [+] Do a quick search and make sure the bug has not been reported yet.
- [+] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [+] Finally, be nice and have fun!.

### Description

The plugin does not work correctly when the text was written in Russian. In particular, return does not work after converting text into a header and other types of blocks.

### Environment

* Editor.js version: 2.25.0
* Plugins you use with their versions: 1.0.1 and 2.0.12
* Device, Browser, OS: chrome, win10

### Current behavior

We write 1 paragraph of text
Convert 1 paragraph to heading
Change the keyboard layout to Russian (or another)
Press cmd + z
**Nothing happens**

### Expected behavior

We write 1 paragraph of text
Convert 1 paragraph to heading
Change the keyboard layout to Russian (or another)
Press cmd + z
**Paragraph 1 became text again**

**Comment by miguelnietoa** [comment]
The fix is now available in version `2.0.13` 👍🏻
