### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'holder')

### ISSUE THREAD

**Issue by khanakia** [kommitters/editorjs-undo#180]
### Precheck

- [ X] Do a quick search and make sure the bug has not been reported yet.
- [ X] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ X] Finally, be nice and have fun!.

### Description

When there is the last element to undo editor.js throws an error because of empty state. Please refer to this issue https://github.com/codex-team/editor.js/issues/2090

### Environment

* Editor.js version: v2.26.4
* Plugins you use with their versions: 2.0.15
* Device, Browser, OS: Chrome

### Current behavior

When there is the last element to undo editor.js throws an error because of empty state. Please refer to this issue https://github.com/codex-team/editor.js/issues/2090

https://user-images.githubusercontent.com/2174170/209191228-867814a2-9c63-4c2a-a3a7-ed96e999d500.mov

### Expected behavior

It should not show the error.

### Additional context

[Add any other context about the problem here.](https://github.com/codex-team/editor.js/issues/2090)

**Comment by khanakia** [comment]
I have created a pull request https://github.com/kommitters/editorjs-undo/pull/179

**Comment by miguelnietoa** [comment]
Fixed through #190 in version `2.0.19`.

Thank you @khanakia for contributing!

**Comment by miguelnietoa** [comment]
Sorry! I forgot to include the bundle file so this issue is actually solved in version `2.0.20` 👍🏻
