### ISSUE TITLE
Save request in read-mode when using multiple editors

### ISSUE THREAD

**Issue by egg-** [kommitters/editorjs-undo#207]
### Precheck

- [X] Do a quick search and make sure the bug has not been reported yet.
- [X] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [X] Finally, be nice and have fun!.

### Description

When using multiple editorjs on a single page, when changing the readonly setting of some editors, an error is returned saying that it cannot be saved in read-only mode.

### Environment

* Editor.js version: 2.26.5
* Plugins you use with their versions: 2.0.20
* Device, Browser, OS:

### Current behavior

The operation is find, but the error is reported in the console.

```javascript
Editor.js:2 Uncaught (in promise) Error: Editor's content can not be saved in read-only mode
    at n.value (editor.js:2:1)
    at e.save (editor.js:2:1)
    at Undo.registerChange (index.js:128:1)
    at index.js:54:1
    at Observer.<anonymous> (observer.js:21:1)
    at observer.js:87:1
``` 

### Expected behavior

Check the editor's read mode and do not request save in read mode.

### Additional context

-

**Comment by miguelnietoa** [comment]
Hello! We just released [v2.0.22](https://www.npmjs.com/package/editorjs-undo/v/2.0.22) which includes the fix for this issue!
Thank you @egg- for making this contribution 👏🏻
