### ISSUE TITLE
Can't undo the deleted block

### ISSUE THREAD

**Issue by htoann** [kommitters/editorjs-undo#209]

**Comment by miguelnietoa** [comment]
Hello @htoann could you provide more context?

**Comment by liexierra** [comment]
Same problem. If you create some blocks (e.g. paragraphs), and after that, you manually delete one of them, undo won't revert deleted block back. In console i see that message `There is no block at index `1``

**Comment by juanmagiraldor** [comment]
Hello! We just released [v2.0.23](https://www.npmjs.com/package/editorjs-undo/v/2.0.23) which includes the fix for this issue!
Thank you @htoann  for making this contribution 👏🏻
