### ISSUE TITLE
How do I use api to trigger actions

### ISSUE THREAD

**Issue by chf-gh** [kommitters/editorjs-undo#218]
I want to use api to trigger undo/redo actions, what should I do?

**Comment by MarioRodriguezS** [comment]
@chf-gh Thank you for reporting the issue. To trigger undo or redo actions through the API you could assign a variable to the 'Undo' instance within the onReady() callback. Then, you can employ this variable anywhere within your code and do `Undo.undo` or `Undo.redo`. For a practical example, please refer to the CodeSandbox demonstration provided.

[code sandbox example](https://codesandbox.io/s/editorjs-undo-api-pd3476?file=/src/index.mjs)
