### ISSUE TITLE
Doesn't work on other keyboard layouts

### ISSUE THREAD

**Issue by envyboxkf** [kommitters/editorjs-undo#24]
if the keyboard is in Russian, it doesn't work.

I suggest using event.code = KeyZ and event.code = KeyY

**Comment by groteworld** [comment]
A better suggestion would be to use `metaCode + Shift + Z` for redo

**Comment by juanhurtado10** [comment]
Hey @envyboxkf @groteworld @einerzg 


A new issue to address this improvement has been created (#48)
Please, add your thoughts there, and let's discuss the proposed solution :)

Best!

-------
Closing this in favor of #48
