### ISSUE TITLE
undo functionality doesn't work when splitting text by pressing enter

### ISSUE THREAD

**Issue by abdallahalsamman** [kommitters/editorjs-undo#243]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

if I put the cursor in the middle of paragraph text and hit enter, I will have a new paragraph with the right part of text.

Now if I hit ctrl + z, nothing happens.

### Environment

* Editor.js version: 2.0.26  
* Plugins you use with their versions:
        "@editorjs/editorjs": "^2.29.0",
        "@editorjs/header": "^2.8.1",
        "@editorjs/list": "^1.9.0",
        "@editorjs/table": "^2.3.0",
        "@tailwindcss/typography": "^0.5.10",
        "editorjs-undo": "^2.0.26",

* Device, Browser, OS: Ubuntu, Firefox Snap 123.0.1 (64-bit)

### Current behavior

Nothing happens on ctrl + z

### Expected behavior

Undo show remove the new paragraph and put the text how it was

**Comment by MarioRodriguezS** [comment]
@abdallahalsamman Thank you for reporting the issue! We've been trying to reproduce it without success. Could you please provide more context or a video? Additionally, if there are any console messages associated with the issue, they would be helpful. I've attached a video showing our attempt.

https://github.com/kommitters/editorjs-undo/assets/64106728/dfe376ac-3bb3-4130-a54c-e5f8f02fd027

**Comment by MarioRodriguezS** [comment]
@abdallahalsamman While attempting to reproduce the reported issue, we found a related issue related to the redo action, which has already been worked on pull request #244. However, we have not yet been able to reproduce your reported issue.

**Comment by abdallahalsamman** [comment]
I will update the package and test to see if the issue is still happening

**Comment by abdallahalsamman** [comment]
@MarioRodriguezS it's still happening here even after I upgrade to 2.0.26

**Comment by abdallahalsamman** [comment]
[Screencast from 26-03-24 23:20:27.webm](https://github.com/kommitters/editorjs-undo/assets/12014839/56812da3-4236-47cd-aa83-481306213397)

**Comment by miguelnietoa** [comment]
@abdallahalsamman The plugin expects `CMD` rather than `CTRL`. CMD will be set up automatically as Ctrl or ⌘ depending on the client OS. Try updating the shortcuts: 
```js
shortcuts: {
    undo: 'CMD+Z',
    redo: 'CMD+SHIFT+Z'
}
```

**Comment by MarioRodriguezS** [comment]
@abdallahalsamman Indeed, there is a bug when performing the action you mentioned. Once you have properly set up the plugin, you will encounter it. We will be working on fixing it as soon as possible.
