### ISSUE TITLE
EditorJs-undo compatibility with ReactJs component?

### ISSUE THREAD

**Issue by armandasalmd** [kommitters/editorjs-undo#46]
I am using `react-editor-js` npm package and I would like to extend it with undo.

```js
const handleReady = (editor) => {
        new Undo({ editor });
};

<EditorJs
        instanceRef={instance => (editorJsRef.current = instance)}
        placeholder="Start typing what's in your head..."
        tools={EDITOR_JS_TOOLS}
        data={data}
        onReady={handleReady}
/>
```

According to your documentation, this should work. But error breaks the page:
![image](https://user-images.githubusercontent.com/17089888/123096953-8c719880-d427-11eb-83d2-1bdc0f727ffc.png)

In this case  `e = this.editor.configuration.holder`.

`holder` property in editor instance I am passing in `handleReady` function is a string with editor container ID. But library code references it as DOM element.

This workaround works (converting element ID to DOM element):
```js
const handleReady = (editor) => {
        let temp = document.getElementById(editor.configuration.holder);
        editor.configuration.holder = temp;

        new Undo({ editor });
};
```

But I don't think that I should override this.
Also can you update README.md to show an example how to integrate this with https://www.npmjs.com/package/react-editor-js?

**Comment by juanhurtado10** [comment]
Hey @armandasalmd 

Thanks for reporting. We will check this out. 

Any solution on your end is welcome, just push your code in a PR :)

Best!

**Comment by juanhurtado10** [comment]
Hey @armandasalmd 

Since `v0.2.0` the plugin is fully compatible with `react-editor-js`.

Best,
Juan
