### ISSUE TITLE
Ctrl+Z will make editor scroll to top [Firefox]

### ISSUE THREAD

**Issue by conanliuhuan** [kommitters/editorjs-undo#75]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

If an article is very long, and scrollbar is in the middle of the article, press Ctrl+Z will make editor scroll to top.

this experience is not good

### Environment

* Editor.js version: 2.22.2
* Plugins you use with their versions: No plugin enabled
* Device, Browser, OS: Firefox Windown10, PC

### Current behavior

Press Ctrl+Z will scroll to top

### Expected behavior

Press Ctrl+Z would not scroll to any where

### Additional context

Firefox will cause this problem, Chrome is ok

**Comment by yammycode** [comment]
I have the same problem

**Comment by MarioRodriguezS** [comment]
@conanliuhuan, @yammycode  Thanks a lot for report the issue! 
Could you please add more details about when the issue raises?, I have been trying to reproduce the issue, but I have not been able to do it. In the following GIF, I try to reproduce the issue with CTRL+Z and CTRL+Y. 

![issue](https://user-images.githubusercontent.com/64106728/146200635-a167935c-7250-4f5d-810c-6e146bee1975.gif)


Best, Mario.

**Comment by yammycode** [comment]
@MarioRodriguezS 
https://disk.yandex.ru/i/A5_YKMb5MmEZ5A
In my case i use editorjs inside laravel nova admin.
May be to reproduce the problem, you have to place some content before and after the editor instance...

**Comment by yammycode** [comment]
It may be necessary to remember the current position of the scroll before undo/redo operation and to force scroll after  re-rendering of editor content? 
Or add several callbacks before and after this operations for self-implementation if necessary.

**Comment by adampatterson** [comment]
Unrelated but related.

Undoing will cause embedded content to re-render, which is a bit jarring.

**Comment by yammycode** [comment]
Yes)) You can even see it in firefox - the page blinks for a moment. If only the affected blocks were updated, not all editor content, it would be fantastic.

**Comment by conanliuhuan** [comment]
@MarioRodriguezS This bug won't trigger everytime. In the following video, there was a fault several times before, and then it was normal.

https://user-images.githubusercontent.com/26618275/146708028-6ae8d184-3bb5-4daf-a571-8493aae1bf6d.mp4

**Comment by MarioRodriguezS** [comment]
@conanliuhuan @adampatterson @yammycode Hi there! 
We just released a beta version of editorjs-undo (v2.0.0-rc.0). We expect that this helps to solve your issues, please report any bug or behavior issue. 

More information may be found in the Readme file. Thanks!!

Best,
Mario

**Comment by adampatterson** [comment]
@MarioRodriguezS  I may need to test further, and am not 100% sure this is an issue with your Undo plugin but I have a number of other plugins installed and it seemed to have some strange issues.

Without anything else enabled the undo I think worked perfectly.

```javascript
const editor = new EditorJS({
    holder: 'contentEditor',
    data: JSON.parse(content),
    placeholder: 'Write something awesome!',

    onReady: () => {

        new Undo({ editor });

        const saveButton = document.getElementById('saveButton')
        saveButton.addEventListener('click', function (event) {
            editor.save().then((outputData) => {
                console.log('Article data: ', outputData)
                document.getElementById('editorBlock').value = JSON.stringify(outputData)
            }).catch((error) => {
                console.log('Saving failed: ', error)
            })
        })
    }
})
```

And with basically the kitchen sink the undo order is a bit mixed up:

Maybe this is expected as it undoes the active block just fine.

![Screen Capture on 2022-01-30 at 10-23-20](https://user-images.githubusercontent.com/31537/151710138-6448ea41-1e2f-4e3d-bbed-328c162a564e.gif)

```javascript
import EditorJS from '@editorjs/editorjs' // //https://editorjs.io/

const Header = require('@editorjs/header') // https://github.com/editor-js/header
const Embed = require('@editorjs/embed') // https://github.com/editor-js/embed
const LinkTool = require('@editorjs/link') // https://github.com/editor-js/link
const ImageTool = require('@editorjs/image') // https://github.com/editor-js/image
const List = require('@editorjs/list') // https://github.com/editor-js/list
const Quote = require('@editorjs/quote') // https://github.com/editor-js/quote
const Underline = require('@editorjs/underline') // https://github.com/editor-js/underline
const InlineCode = require('@editorjs/inline-code') // https://github.com/editor-js/inline-code
const Marker = require('@editorjs/marker') // https://github.com/editor-js/marker
const CodeTool = require('@editorjs/code') // https://github.com/editor-js/code
const Delimiter = require('@editorjs/delimiter') // https://github.com/editor-js/delimiter
const Warning = require('@editorjs/warning') // https://github.com/editor-js/warning
const DragDrop = require('editorjs-drag-drop') // https://github.com/kommitters/editorjs-drag-drop
const Undo = require('editorjs-undo') // https://github.com/kommitters/editorjs-undo


const content = document.getElementById('editorBlock').value

const editor = new EditorJS({
    holder: 'contentEditor',
    data: JSON.parse(content),
    placeholder: 'Write something awesome!',
    tools: {
        header: {
            class: Header,
            shortcut: 'CMD+SHIFT+H',
            config: {
                levels: [1, 2, 3, 4, 5],
                defaultLevel: 3
            }
        },
        underline: Underline,
        delimiter: Delimiter,
        code: CodeTool,
        list: {
            class: List,
            inlineToolbar: true,
        },
        quote: {
            class: Quote,
            inlineToolbar: true,
            shortcut: 'CMD+SHIFT+O',
        },
        Marker: {
            class: Marker,
            shortcut: 'CMD+SHIFT+M',
        },
        inlineCode: {
            class: InlineCode,
            shortcut: 'CMD+SHIFT+C',
        },
        warning: {
            class: Warning,
            inlineToolbar: true,
            shortcut: 'CMD+SHIFT+W',
            config: {
                titlePlaceholder: 'Title',
                messagePlaceholder: 'Message',
            },
        },
        embed: {
            class: Embed,
            inlineToolbar: true,
            config: {
                services: {
                    // @todo #212 https://github.com/adampatterson/maker/issues/212
                    youtube: true,
                    vimeo: true,
                    twitter: false,
                    instagrarm: false,
                    facebook: false,
                    codepen: false,
                    pinterest: false, // Not working
                }
            }
        },
        linkTool: {
            class: LinkTool,
            config: {
                additionalRequestHeaders: {
                    'X-CSRF-TOKEN': window.contentEditor.token
                },
                endpoint: window.contentEditor.fetchUrl,
            }
        },
        // image: SimpleImage,
        image: {
            class: ImageTool,
            config: {
                types: 'image/*',
                additionalRequestData: {
                    '_token': window.contentEditor.token
                },
                additionalRequestHeaders: {
                    'X-CSRF-TOKEN': window.contentEditor.token
                },
                endpoints: {
                    byFile: window.contentEditor.fetchImageByFile, // Your backend file uploader endpoint
                    byUrl: window.contentEditor.fetchImageByUrl, // Your endpoint that provides uploading by Url
                }
            }
        },
    },
    onReady: () => {

        new Undo({editor})
        new DragDrop(editor)

        const saveButton = document.getElementById('saveButton')
        saveButton.addEventListener('click', function (event) {
            editor.save().then((outputData) => {
                console.log('Article data: ', outputData)
                document.getElementById('editorBlock').value = JSON.stringify(outputData)
            }).catch((error) => {
                console.log('Saving failed: ', error)
            })
        })
    }
})

```

**Comment by adampatterson** [comment]
I will do some more testing to see if I can narrow it down to anything more specific!
