### ISSUE TITLE
Caret should maintain its current position during CMD+Z and CMD+Y operations within a text block

### ISSUE THREAD

**Issue by trevrdspcdev** [kommitters/editorjs-undo#84]
CMD+Z and CMD+Y operations on text selections within a text block cause the caret to unexpectedly jump to the end of the current text block rather than remaining in its current location.

CMD+Z and CMD+Y operations on text selections within a text block should **not** cause the caret to unexpectedly jump to the end of the current text block. The caret should remain in the position it was in when the CMD+Z or CMD+Y operation was initiated.

If text deleted from within a text block is restored using CMD+Z, the restored text should be highlighted, indicating that it is currently selected.

- If the user then presses the left or right arrow on their keyboard, the caret should be appear at the beginning or end of the restored text, respectively.
- If the user begins entering new characters while a restored selection is highlighted, the restored selection should be replaced and the caret should appear to the right of the first character entered.
- If the user presses CMD+Y to re-delete a restored (and highlighted) selection, the caret should appear immediately to the left of where the first character in the deleted selection was located.

The caret currently jumps to the end of the current text block when CMD+Z and CMD+Y are used, as shown below:

https://user-images.githubusercontent.com/19937217/152803643-5b5024a5-879b-486b-9a58-870ad39e3975.mov

The caret should maintain its position during CMD+Z and CMD+Y operations, as shown below:

https://user-images.githubusercontent.com/19937217/152804766-8ecfd431-d34e-42da-9e18-53fef4f7986c.mov

**Comment by MarioRodriguezS** [comment]
@trevrdspcdev Thanks for report the issue!, it was solved, and it will be available in the next release soon. 
![caret](https://user-images.githubusercontent.com/64106728/155024711-970e89f2-7425-4297-af9e-2c2d58b8d729.gif)


Best,
Mario
