### ISSUE TITLE
Library listening to all click events on the DOM

### ISSUE THREAD

**Issue by gyenabubakar** [kommitters/editorjs-undo#85]
### Description

After instantiating the Undo class in `onReady()`, every click on the DOM (anywhere other than the EditorJS editor itself) triggers a save event on the editor, this doesn't happen when I remove the `editorjs-undo` library.

![editorjs](https://user-images.githubusercontent.com/26672526/154167300-1146c878-320f-4447-9bdc-ff6f55bce991.png)

### Environment

* Editor.js version: **2.23.2**

* Plugins you use with their versions:

Embed, Table, List, Warning, Code, LinkTool, Raw, Header, Quote, Marker, CheckList, Delimiter, InlineCode, SimpleImage

* Device, Browser, OS: HP Elitebook 8470p, Chrome, Ubuntu

Is there a way to scope the click events to the editor container only, so clicks outside the editor container doesn't trigger the save event?

I'm worried that this behaviour might affect performance.

**Comment by MarioRodriguezS** [comment]
@gyenabubakar Thanks for report the issue!,
it was solved, and it will be added in the new version of editorjs-undo (v2.0.0-rc.2) soon.

Best,
Mario
