### ISSUE TITLE
Undo tries to save when readOnly is toggled to true

### ISSUE THREAD

**Issue by hlynurstef** [kommitters/editorjs-undo#87]
### Description

When you initialize the editorjs instance with `readOnly: false` and then later toggle it to true using `editor.readOnly.toggle()` then this library still tries to call `editor.save()` causing an error.

This error does not happen when `editorjs-undo` is not installed.

![image](https://user-images.githubusercontent.com/15615089/154232273-b2404c89-3543-4d72-bd75-c2e9fb0a0651.png)

### Environment

* Editor.js version: 2.23.2
* Plugins you use with their versions:
```
    "@editorjs/embed": "2.5.0",
    "@editorjs/header": "2.6.2",
    "@editorjs/image": "2.6.2",
    "@editorjs/list": "1.6.2",
    "@editorjs/paragraph": "2.8.0",
    "@editorjs/table": "2.0.1",
    "editorjs-undo": "1.0.1",
```
* Device, Browser, OS: 
Device: Macbook M1 Pro
Browser: Chrome Version 98.0.4758.102 (Official Build) (arm64)
OS: macOS Monterey version 12.1

### Current behavior

Reproduction steps:
1. Create EditorJS instance with readOnly: false
2. Inject instance into Undo
3. Toggle editor to readOnly mode using editor.readOnly.toggle()
4. Observe the error

### Expected behavior

The library should know how to handle readOnly mode and respond accordingly when readOnly mode is toggled between true/false

**Comment by MarioRodriguezS** [comment]
@hlynurstef Thanks for report the issue!, 
it was solved, and it was added in the new version of editorjs-undo(v2.0.0-rc.1).

Best,
Mario

**Comment by hlynurstef** [comment]
@MarioRodriguezS thanks! I'll give it a try.
