### ISSUE TITLE
Plugin still trying to save after the editor instance has been destroy

### ISSUE THREAD

**Issue by Rathpanha** [kommitters/editorjs-undo#9]
This problem is duplicate with [PR](https://github.com/kommitters/editorjs-undo/pull/7) and it does not fix the problem.
It was my bad that I didn't review it carefully. The problem is still the same that the plugin still trying to call the editor's save API after the editor instance has been destroyed.

![image](https://user-images.githubusercontent.com/24370142/87502021-c28c9100-c68a-11ea-908c-2eee122eecd7.png)

**Comment by nicolasgaviria** [comment]
Hi @Rathpanha, can you tell me the process you're performing to get this error? Also, can you make sure you're using the last version of the plugin? 

Thanks in advance!

**Comment by Rathpanha** [comment]
Hi @nicolasgaviria, I am using react. I need to destroy the editor instance to clear all bind events to the editor in `componentWillUnmount`. It's easy to reproduce the error, just call the editor destroy API like my code below:

![image](https://user-images.githubusercontent.com/24370142/87641680-a6641f00-c772-11ea-9015-f38ebdda842a.png)

One thing I noticed is that when I click go back button of the browser the `registerChange()` is not called, but when I click on another link in my project, `registerChange()` is called and cursed this error, because of the editor instance has already been destroyed.

**Comment by nicolasgaviria** [comment]
@Rathpanha Thank you! I'll check it ASAP.

**Comment by nicolasgaviria** [comment]
@Rathpanha Hey! So sorry for the delay, I've been incredibly busy last days. I just created a new [branch](https://github.com/kommitters/editorjs-undo/tree/version-0.1.4) with something I think can solve your issue. Can you please check it out and tell me if it works for you?

Thanks!

**Comment by Rathpanha** [comment]
Hi @nicolasgaviria , I tested and problem is still there. I'll try to help you look into this error as well. :)

**Comment by nicolasgaviria** [comment]
@Rathpanha Hey! @Jmzp just pushed to the [branch](https://github.com/kommitters/editorjs-undo/pull/13), can you check if his solution works for you? Thanks!

**Comment by Rathpanha** [comment]
@nicolasgaviria @Jmzp Thank you, this does fix the problem this time 👍 😀
